FROM ubi8
USER root
COPY cyclictest/cmd.sh /root
COPY common-libs /root/common-libs
RUN RT_TEST=$(curl -L https://www.rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/ 2>/dev/null | sed -n -r 's/.*href=\"(rt-tests-2.5-1.*.rpm)\".*/\1/p') \
    && yum -y install https://www.rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/${RT_TEST} \
    && yum -y install which python3 numactl-libs \
    && ln -s $(which python3) /usr/local/bin/python \
    && yum clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
