FROM ubi9
USER root
COPY rtla/cmd.sh /root
COPY common-libs /root/common-libs
RUN yum -y install https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/libtraceevent-1.5.3-3.el9.x86_64.rpm \
    && yum -y install https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/libtracefs-1.3.1-1.el9.x86_64.rpm \
    && yum -y install https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/rtla-5.14.0-350.el9.x86_64.rpm \
    && yum -y install which numactl-libs \
    && yum clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
